version: '3'

services:
  app:
    image: 'tournament:latest'
    build:
      context: .
    container_name: tournament-app
    depends_on:
      - db
    ports:
      - 9090:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=toor
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: tournament
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
    ports:
      - 5433:5432
